---
driver:
  name: vagrant
  network:
    - [ "forwarded_port", { guest: 80, host: 8080 } ]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - 'recipe[dani-serv::default]'
    attributes:
      dani-serv:
        password: '$6$0Bncxpot$2xaFjK6Y3sp6e1o4rDTW5/dJkYqT9pV8xFk8NPnugRnDS5rzOzeFFm5c9pKLQlES2SIt3qGfOJ.0CNXYf6GJ01'
